import {
  PatientDossier,
  MedicalDocumentItem,
  TimelineEventItem,
  SpecialtySummaryItem,
  FunctionalCapacityItem,
  GutachtenDraftVariant,
  QualityControlItem,
  ConsensusModelOutput,
} from "./gutachtenTypes";

export const initialPatientDossier: PatientDossier = {
  patientId: "PAT-2026-8809",
  firstName: "Thomas",
  lastName: "Müller",
  birthDate: "14.11.1982",
  insuranceNumber: "X120938475",
  caseId: "BG-2026-9901-A",
  insuranceProvider: "Techniker Krankenkasse (TK)",
  commissioningEntity: "BGHM (Berufsgenossenschaft Holz und Metall)",
  accidentDate: "12.03.2025",
  subjectTitle: "Posttraumatischer Bandscheibenvorfall L4/L5 nach Hebeerschütterung mit L5-Radikulopathie",
  totalPages: 248,
  totalSizeMb: 184.5,
  uploadedDocuments: [
    {
      id: "doc-1",
      filename: "Klinikum_Koeln_Entlassungsbericht_2025-03-20.pdf",
      category: "hospital_report",
      categoryLabel: "Krankenhaus Entlassungsbericht",
      date: "20.03.2025",
      facility: "Klinikum Köln Merheim - Klinik für Neurochirurgie",
      physician: "Prof. Dr. med. V. Schmidt",
      pages: 18,
      fileSizeMb: 14.2,
      ocrQuality: 98,
      language: "de",
      isScanned: false,
      summary: "Stationäre Aufnahme nach akutem Hebstrauma. Befund zeigt mediolaterale Diskushernie L4/L5 links mit Bedrängung der L5-Wurzel.",
      keyDiagnoses: ["ICD-10 M51.1 Lendenbandscheibenschaden mit Radikulopathie", "ICD-10 G55.1 Kompression von Nervenwurzeln"],
    },
    {
      id: "doc-2",
      filename: "MRT_Lendenwirbelsaeule_Radiologie_2025-03-28.pdf",
      category: "mri_scan",
      categoryLabel: "MRT Befund LWS 1.5T",
      date: "28.03.2025",
      facility: "Radiologisches Zentrum Köln-Süd",
      physician: "Dr. med. H. Weber (Radiologe)",
      pages: 6,
      fileSizeMb: 8.5,
      ocrQuality: 96,
      language: "de",
      isScanned: true,
      summary: "Ausgeprägter Protoplasmaprotrusions-Prokollaps L4/L5 links dorso-lateral. Keinerlei höhergradige Spondylarthrose.",
      keyDiagnoses: ["Bandscheibenvorfall L4/L5 links", "Keine signifikante Vorschädigung L1-L3"],
    },
    {
      id: "doc-3",
      filename: "Hausarzt_Praxis_Dr_Krueger_Chronik.pdf",
      category: "gp_report",
      categoryLabel: "Hausarzt Verlaufsdokumentation",
      date: "10.04.2025",
      facility: "Praxis Dr. med. F. Krüger (Allgemeinmedizin)",
      physician: "Dr. med. F. Krüger",
      pages: 34,
      fileSizeMb: 22.1,
      ocrQuality: 92,
      language: "de",
      isScanned: true,
      summary: "Regelmäßige Konsultationen wegen Lumboischialgie links, Fußheberparese Grad 4/5, schmerzbedingte Arbeitsunfähigkeit seit 12.03.2025.",
      keyDiagnoses: ["Lumboischialgie links L5", "M45.9 Spondylitis nicht spezifiziert (Ausschluss)"],
    },
    {
      id: "doc-4",
      filename: "Neurologisches_Konsil_EMG_NLG_2025-05-14.pdf",
      category: "specialist_report",
      categoryLabel: "Neurologischer Befund & EMG/NLG",
      date: "14.05.2025",
      facility: "Neurologische Praxis Dr. med. S. Braun",
      physician: "Dr. med. S. Braun (Neurologin)",
      pages: 12,
      fileSizeMb: 9.8,
      ocrQuality: 99,
      language: "de",
      isScanned: false,
      summary: "EMG M. tibialis anterior links zeigt chronisch-neurogene Umbaumuster sowie Denervierungspotenziale bei L5-Wurzelkompression.",
      keyDiagnoses: ["Chronische L5-Radikulopathie links", "NLG N. peroneus am fibularisköpfchen verlangsamt"],
    },
    {
      id: "doc-5",
      filename: "Reha_Abschlussbericht_Bad_Sassendorf.pdf",
      category: "rehabilitation",
      categoryLabel: "Stationärer Reha-Entlassbericht",
      date: "22.06.2025",
      facility: "Klinik am Quellenpark Bad Sassendorf",
      physician: "Dr. med. M. Neumann (Sozialmediziner)",
      pages: 42,
      fileSizeMb: 31.0,
      ocrQuality: 95,
      language: "de",
      isScanned: false,
      summary: "3-wöchige ganztägige Reha. Mäßige Schmerzlinderung von NRS 8 auf NRS 5 unter Intensivphysiotherapie. Belastungsfähigkeit unter 3 Std/Tag für schwere Hebearbeiten.",
      keyDiagnoses: ["Funktionelle Leistungseinschränkung des LWS-Abschnitts", "MdE-Einschätzung 20% im Erwerbsleben"],
    },
    {
      id: "doc-6",
      filename: "OP_Bericht_Mikrochirurgische_Sequestrektomie.pdf",
      category: "operative_report",
      categoryLabel: "Operativer Operationsbericht",
      date: "04.04.2025",
      facility: "Sankt Vinzenz Hospital Neurochirurgie",
      physician: "Dr. med. A. Vogel",
      pages: 8,
      fileSizeMb: 6.4,
      ocrQuality: 97,
      language: "de",
      isScanned: false,
      summary: "Mikrochirurgische Dekompression und Sequestrektomie L4/L5 links ohne intraoperative Komplikationen. Abgang der Wurzel L5 dargestellt und entlastet.",
      keyDiagnoses: ["Z.n. Sequestrektomie L4/L5 links"],
    },
    {
      id: "doc-7",
      filename: "Labor_Analysen_Entzuendungsmarker_Blutbild.pdf",
      category: "lab_report",
      categoryLabel: "Laborbefunde & Entzündungswerte",
      date: "15.03.2025",
      facility: "Synlab Labormedizin Köln",
      physician: "Dr. rer. nat. K. Fischer",
      pages: 14,
      fileSizeMb: 11.2,
      ocrQuality: 100,
      language: "de",
      isScanned: false,
      summary: "Normales CRP (<5 mg/l), BSG 8/18 mm n.W., kein Hinweis auf rheumatische oder infektiöse Genese der Wirbelsäulenbeschwerden.",
      keyDiagnoses: ["Unauffällige Entzündungsparameter"],
    },
    {
      id: "doc-8",
      filename: "Medikationsplan_Schmerztherapie.pdf",
      category: "prescriptions",
      categoryLabel: "Medikationsplan & BTM Rezeptur",
      date: "01.07.2025",
      facility: "Schmerzzentrum Köln-Mitte",
      physician: "Dr. med. P. Hoffmann",
      pages: 5,
      fileSizeMb: 3.8,
      ocrQuality: 94,
      language: "de",
      isScanned: true,
      summary: "Pregabalin 150mg 1-0-1, Tapentadol 50mg retard 1-0-1, Ibuprofen 600mg bei Bedarf. Gute Verträglichkeit.",
      keyDiagnoses: ["Neuropathischer Schmerz bei Radikulopathie"],
    },
    {
      id: "doc-9",
      filename: "BG_Schriftverkehr_Unfallanzeige.pdf",
      category: "insurance_corr",
      categoryLabel: "BG Schriftverkehr & Unfallanzeige",
      date: "13.03.2025",
      facility: "BGHM Berufsgenossenschaft Holz und Metall",
      physician: "Sachbearbeitung BGHM",
      pages: 15,
      fileSizeMb: 12.0,
      ocrQuality: 91,
      language: "de",
      isScanned: true,
      summary: "Unfallmeldung durch Arbeitgeber (Metallbau GmbH). Anlass: Heben einer 45 kg schwerer Kiste unter Verwindung des Rumpfes.",
      keyDiagnoses: ["Anerkannter Arbeitsunfall V.-Nr. 2025-9901"],
    },
    {
      id: "doc-10",
      filename: "AU_Bescheinigungen_Zusammenfassung.pdf",
      category: "sick_leave",
      categoryLabel: "Arbeitsunfähigkeitsbescheinigungen",
      date: "01.08.2025",
      facility: "Techniker Krankenkasse",
      physician: "Diverse Doktoren",
      pages: 22,
      fileSizeMb: 18.1,
      ocrQuality: 90,
      language: "de",
      isScanned: true,
      summary: "Durchgehende Arbeitsunfähigkeit von 12.03.2025 bis laufend (Stand August 2025). Krankengeldbezug.",
      keyDiagnoses: ["Laufende AU M51.1"],
    },
    {
      id: "doc-11",
      filename: "Psychiatrisches_Zusatzgutachten_Schmerz.pdf",
      category: "psychiatric",
      categoryLabel: "Psychiatrisches / Psychosomatisches Gutachten",
      date: "18.07.2025",
      facility: "Institut für Psychosomatik Köln",
      physician: "Dr. med. E. Franke",
      pages: 28,
      fileSizeMb: 24.5,
      ocrQuality: 96,
      language: "de",
      isScanned: false,
      summary: "Sekundäre Anpassungsstörung mit gedrückter Stimmung bei chronischer Schmerzsymptomatik. Kein Nachweis einer Begehrensneurose.",
      keyDiagnoses: ["ICD-10 F43.2 Anpassungsstörung", "Chronische Schmerzstörung mit somatischen und psychischen Faktoren"],
    },
    {
      id: "doc-12",
      filename: "Ueberweisungen_und_Konsilberichte.pdf",
      category: "referrals",
      categoryLabel: "Überweisungen & Konsilberichte",
      date: "02.05.2025",
      facility: "Diverse Fachärzte",
      physician: "Dr. med. F. Krüger",
      pages: 18,
      fileSizeMb: 13.9,
      ocrQuality: 89,
      language: "de",
      isScanned: true,
      summary: "Überweisungen an Orthopädie, Neurologie, Radiologie, Schmerztherapie.",
      keyDiagnoses: ["Konsiliarische Klärung erforderlich"],
    },
    {
      id: "doc-13",
      filename: "CT_LWS_PostOP_Kontrolle.pdf",
      category: "ct_scan",
      categoryLabel: "CT LWS Post-OP Kontrolle",
      date: "12.05.2025",
      facility: "Radiologie Am Dom",
      physician: "Dr. med. T. Richter",
      pages: 8,
      fileSizeMb: 7.2,
      ocrQuality: 97,
      language: "de",
      isScanned: false,
      summary: "Regelrechte postoperative Verhältnisse nach Sequestrektomie L4/L5 links. Kein verbliebener freier Sequester.",
      keyDiagnoses: ["Z.n. OP L4/L5 ohne Rezidiv im CT"],
    },
    {
      id: "doc-14",
      filename: "Roentgen_Ganzwirbelsaeule_Stand.pdf",
      category: "radiology_xray",
      categoryLabel: "Röntgen Ganzwirbelsäule Stand",
      date: "16.03.2025",
      facility: "Orthopädische Praxisklinik Köln",
      physician: "Dr. med. G. Baum",
      pages: 6,
      fileSizeMb: 4.8,
      ocrQuality: 95,
      language: "de",
      isScanned: false,
      summary: "Physiologische Lendenlordose. Keine höhergradige Fehlstatik oder Wirbelgleiten (Spondylolisthesis).",
      keyDiagnoses: ["Regelrechte knöcherne Statik"],
    },
  ],
};

export const initialTimelineEvents: TimelineEventItem[] = [
  {
    id: "tl-1",
    date: "12.03.2025",
    doctor: "Dr. med. F. Krüger (Hausarzt)",
    hospital: "Praxis Dr. Krüger Köln",
    specialty: "Allgemeinmedizin / Erstversorgung",
    complaint: "Akut aufgetretener stechender Schmerz im LWS-Bereich mit Ausstrahlung ins linke Bein nach Heben einer 45kg Kiste.",
    diagnosis: "Akute Lumboischialgie links L5",
    icd10: "M54.16",
    treatment: "Intramuskuläre Infiltration, Verordnung von Analgetika, AU-Bescheinigung, Einweisung in Klinik.",
    medication: "Ibuprofen 600mg, Musaril 50mg",
    outcome: "Anhaltend starke Schmerzen NRS 9/10, Gehfähigkeit stark vermindert.",
    followUp: "Sofortige Einweisung Klinikum Köln Merheim",
    sourceDocId: "doc-3",
    sourceDocName: "Hausarzt_Praxis_Dr_Krueger_Chronik.pdf",
    sourcePage: 4,
    confidence: 98,
  },
  {
    id: "tl-2",
    date: "15.03.2025",
    doctor: "Dr. rer. nat. K. Fischer",
    hospital: "Synlab Labormedizin Köln",
    specialty: "Labormedizin",
    complaint: "Ausschluss von Entzündungsparametern oder rheumatischen Schubs.",
    diagnosis: "Kein Anhalt für Spondylodiscitis oder Rheuma",
    icd10: "Z01.7",
    treatment: "Blutentnahme, Entzündungsdiagnostik",
    medication: "Keine",
    outcome: "Normalwerte: CRP <5 mg/l, BSG 8/18 n.W.",
    followUp: "Verlaufskontrolle bei Bedarf",
    sourceDocId: "doc-7",
    sourceDocName: "Labor_Analysen_Entzuendungsmarker_Blutbild.pdf",
    sourcePage: 2,
    confidence: 100,
  },
  {
    id: "tl-3",
    date: "20.03.2025",
    doctor: "Prof. Dr. med. V. Schmidt",
    hospital: "Klinikum Köln Merheim Neurochirurgie",
    specialty: "Neurochirurgie",
    complaint: "Progressive Fußheber- und Großzehenheberparese links (Kraftgrad 3-4/5), Lasègue positive bei 30°.",
    diagnosis: "Mediolaterale Diskushernie L4/L5 links mit L5-Kompressionssyndrom",
    icd10: "M51.1",
    treatment: "Stationäre Schmerztherapie, OP-Indikationsstellung bei neurologischem Defizit.",
    medication: "Novalgin 500mg, Pregabalin 75mg 1-0-1",
    outcome: "OP-Terminierung am 04.04.2025 vereinbart.",
    followUp: "Ambulante Vorbereitung & MRT-Kontrolle",
    sourceDocId: "doc-1",
    sourceDocName: "Klinikum_Koeln_Entlassungsbericht_2025-03-20.pdf",
    sourcePage: 2,
    confidence: 99,
  },
  {
    id: "tl-4",
    date: "28.03.2025",
    doctor: "Dr. med. H. Weber",
    hospital: "Radiologisches Zentrum Köln-Süd",
    specialty: "Neuroradiologie",
    complaint: "Bildgebender Nachweis des L4/L5 Vorfalls im Kernspintomogramm.",
    diagnosis: "Rechtfrischer Protoplasmaprotrusions-Prokollaps L4/L5 links dorso-lateral",
    icd10: "M51.1",
    treatment: "1.5T MRT Lendenwirbelsäule mit Kontrastmittel",
    medication: "Keine",
    outcome: "Radiologisches Äquivalent zur L5-Symptomatik einwandfrei gesichert.",
    followUp: "Übergabe an Neurochirurgie",
    sourceDocId: "doc-2",
    sourceDocName: "MRT_Lendenwirbelsaeule_Radiologie_2025-03-28.pdf",
    sourcePage: 3,
    confidence: 97,
  },
  {
    id: "tl-5",
    date: "04.04.2025",
    doctor: "Dr. med. A. Vogel",
    hospital: "Sankt Vinzenz Hospital Neurochirurgie",
    specialty: "Operative Neurochirurgie",
    complaint: "Operative Intervention bei persistentem Radikulärsyndrom L5 links.",
    diagnosis: "Z.n. mikrochirurgischer Sequestrektomie & Intersegmentalfensterung L4/L5 links",
    icd10: "Z98.8",
    treatment: "Mikrochirurgische Vorfallentfernung und Freilegung der L5-Wurzel",
    medication: "Postoperative Analgesie (Tilidin / Naloxon)",
    outcome: "Komplikationsfreier Verlauf, unmittelbare Besserung des Ruheschmerzes.",
    followUp: "Postoperative Schonung & CT-Kontrolle",
    sourceDocId: "doc-6",
    sourceDocName: "OP_Bericht_Mikrochirurgische_Sequestrektomie.pdf",
    sourcePage: 1,
    confidence: 99,
  },
  {
    id: "tl-6",
    date: "14.05.2025",
    doctor: "Dr. med. S. Braun",
    hospital: "Neurologische Praxis Köln",
    specialty: "Neurologie / Neurophysiologie",
    complaint: "Messung der Nervenleitgeschwindigkeit und Elektromyographie zur Residuum-Beurteilung.",
    diagnosis: "Chronisch-neurogenes Umbaumuster L5 links, Teilerholung der Peroneus-Latenz",
    icd10: "G55.1",
    treatment: "EMG M. tibialis anterior & M. extensor hallucis longus, NLG N. peroneus",
    medication: "Pregabalin 150mg 1-0-1",
    outcome: "Mäßige Restsymptomatik mit Taubheitsgefühl im L5-Dermatom.",
    followUp: "Stationäre Rehabilitation empfohlen",
    sourceDocId: "doc-4",
    sourceDocName: "Neurologisches_Konsil_EMG_NLG_2025-05-14.pdf",
    sourcePage: 6,
    confidence: 96,
  },
  {
    id: "tl-7",
    date: "22.06.2025",
    doctor: "Dr. med. M. Neumann",
    hospital: "Klinik am Quellenpark Bad Sassendorf",
    specialty: "Rehabilitationsmedizin & Sozialmedizin",
    complaint: "Abschlussbeurteilung nach 3-wöchiger medizinischer Rehabilitation.",
    diagnosis: "Persistierende Bewegungseinschränkung LWS, Restsymptomatik L5 links",
    icd10: "M54.16",
    treatment: "Physiotherapie, Medizinische Trainingstherapie (MTT), Ergotherapie",
    medication: "Tapentadol 50mg retard 1-0-1",
    outcome: "Leistungsvermögen für mittelschwere Arbeiten auf 3 bis 6 Std. eingeschränkt. MdE von 20% empfohlen.",
    followUp: "Ambulante Weiterbehandlung & BG-Gutachtenerstellung",
    sourceDocId: "doc-5",
    sourceDocName: "Reha_Abschlussbericht_Bad_Sassendorf.pdf",
    sourcePage: 18,
    confidence: 98,
  },
];

export const initialSpecialtySummaries: SpecialtySummaryItem[] = [
  {
    id: "neurology",
    title: "Neurologie & Neurophysiologie",
    iconName: "Brain",
    majorFindings: [
      "Deutliches L5-Radikulärsyndrom links mit Hypästhesie am Fußrücken und Großzehe.",
      "Leichte Fußheberparese (Kraftgrad 4/5) direkt posttraumatisch gesichert.",
      "EMG vom 14.05.2025 bestätigt chronisch-neurogenes Umbaumuster im M. tibialis anterior links.",
      "Pathologischer Lasègue-Test positiv bei 45 Grad linksseitig.",
    ],
    diagnoses: [
      { code: "M51.1", name: "Lendenbandscheibenschaden mit Radikulopathie L5 links", status: "acute" },
      { code: "G55.1", name: "Nervenwurzelkompression L5", status: "chronic" },
    ],
    progression: "Operative Entlastung zeigte gute Schmerzreduktion im Ruhestand; sensorisches Defizit im Dermatom L5 zeigt verzögerte Regeneration.",
    treatmentResponse: "Gute Schmerzdistanzierung unter Pregabalin 150mg 1-0-1; Motorik stabilisierte sich von Kraftgrad 3/5 auf 4+/5.",
    unresolvedIssues: ["Persistierende Taubheit im Fußrückenbereich links", "Neuropathische Schmerzspitzen bei Wetterwechsel/Kälte"],
    evidenceReferences: [
      { docId: "doc-4", docName: "Neurologisches_Konsil_EMG_NLG_2025-05-14.pdf", page: 6, excerpt: "EMG M. tibialis anterior zeigt neurogene Entladungen passend zur L5-Wurzelläsion." },
      { docId: "doc-1", docName: "Klinikum_Koeln_Entlassungsbericht_2025-03-20.pdf", page: 3, excerpt: "Neurologischer Status: Fußheber schwach, Lasègue 30°." },
    ],
  },
  {
    id: "orthopedics",
    title: "Orthopädie & Traumatologie",
    iconName: "Activity",
    majorFindings: [
      "Schober-Zeichen 10/12 cm, Ott-Zeichen 30/32 cm (eingeschränkte Entfaltung der LWS).",
      "Keine höhergradigen degenerativen Vorveränderungen der angrenzenden Segmente L1-L3 im MRT vom 28.03.2025.",
      "Klare zeitliche und biomechanische Korrelation zwischen Hebstrauma (45kg Kiste) und Vorfall L4/L5.",
      "Klopfschmerz über den Dornfortsätzen L4/L5 und Hartspann der Lendenmuskulatur.",
    ],
    diagnoses: [
      { code: "M54.16", name: "Radikulopathie Lendenbereich", status: "acute" },
      { code: "Z98.8", name: "Z.n. Mikrochirurgischer Sequestrektomie L4/L5", status: "resolved" },
    ],
    progression: "Postoperative Wundheilung p.p. verlaufen. Statische Stabilität der Wirbelsäule erhalten, kein Wirbelgleiten im Röntgenstand.",
    treatmentResponse: "Ansprechen auf physiotherapeutische Rumpfstabilisierung, Hebe- und Trageverbot >10 kg strikt einzuhalten.",
    unresolvedIssues: ["Eingeschränkte LWS-Flexion und Rumpfrotationsschmerz bei Belastung"],
    evidenceReferences: [
      { docId: "doc-2", docName: "MRT_Lendenwirbelsaeule_Radiologie_2025-03-28.pdf", page: 2, excerpt: "Segment L4/L5 zeigt isolierte Herniation ohne relevante Nachbarsegmentdegeneration." },
      { docId: "doc-14", docName: "Roentgen_Ganzwirbelsaeule_Stand.pdf", page: 1, excerpt: "Physiologische Lordose, kein Anhalt für Spondylolisthese." },
    ],
  },
  {
    id: "rehabilitation",
    title: "Rehabilitations- & Sozialmedizin",
    iconName: "ShieldCheck",
    majorFindings: [
      "Abschlussbeurteilung der 3-wöchigen Reha in Bad Sassendorf ergab verbliebene Minderung der Erwerbsfähigkeit (MdE) von 20%.",
      "Einschränkung der körperlichen Belastbarkeit für schwere körperliche Arbeiten auf unter 3 Stunden täglich.",
      "Leistungskriterium für leichte bis mittelschwere Arbeiten in wechselnder Körperhaltung: 6 Stunden und mehr täglich.",
      "Vermeidung von Zwangshaltungen, Erschütterungen, Kälte und Vibrationen erforderlich.",
    ],
    diagnoses: [
      { code: "Z73.6", name: "Einschränkung der Aktivität durch Behinderung", status: "chronic" },
    ],
    progression: "Belastungsaufbau in Reha ergab Stagnation der Schmerztoleranz bei Ergometer-Belastung >100 Watt.",
    treatmentResponse: "Gute Compliance bei Medizinischer Trainingstherapie, jedoch verbliebener Haltungsschmerz.",
    unresolvedIssues: ["Leistungen zur Teilhabe am Arbeitsleben (LTA) / Umschulungsnotwendigkeit prüfen"],
    evidenceReferences: [
      { docId: "doc-5", docName: "Reha_Abschlussbericht_Bad_Sassendorf.pdf", page: 22, excerpt: "MdE um 20 v.H. auf dem allgemeinen Arbeitsmarkt wird sozialmedizinisch empfohlen." },
    ],
  },
  {
    id: "psychiatry",
    title: "Psychiatrie & Psychosomatik",
    iconName: "HeartPulse",
    majorFindings: [
      "Sekundäre Anpassungsstörung (ICD-10 F43.2) im Rahmen der beruflich-finanziellen Unsicherheit und chronischen Schmerzen.",
      "Keine Hinweise auf Aggravation, Neurotisierung oder Rentenbegehren.",
      "Affektiv schwingungsfähig, kooperativ, nachvollziehbare Zukunftsängste bezüglich Berufsausübung.",
    ],
    diagnoses: [
      { code: "F43.2", name: "Anpassungsstörung mit leichter depressiver Reaktion", status: "acute" },
      { code: "F45.41", name: "Chronische Schmerzstörung mit somatischen und psychischen Faktoren", status: "chronic" },
    ],
    progression: "Psychisch stabilisiert durch entlastende Gespräche während der Reha.",
    treatmentResponse: "Ambulante schmerzpsychologische Begleitung wird empfohlen.",
    unresolvedIssues: ["Krankheitsbewältigung bei beruflicher Neuorientierung"],
    evidenceReferences: [
      { docId: "doc-11", docName: "Psychiatrisches_Zusatzgutachten_Schmerz.pdf", page: 12, excerpt: "Keine primär psychogene Schmerzentstehung; psychische Komponente rein sekundärer Natur." },
    ],
  },
  {
    id: "internal_medicine",
    title: "Innere Medizin & Allgemeine Laborwerte",
    iconName: "Stethoscope",
    majorFindings: [
      "Ausschluss entzündlich-rheumatischer Erkrankungen durch unauffällige Laborparameter (CRP <5 mg/l, BSG normal).",
      "Keine Stoffwechselerkrankungen (HbA1c 5.4%, unauffälliger Blutzucker).",
      "Nieren- und Leberwerte unter Schmerzmedikation regelmäßig kontrolliert und normwertig.",
    ],
    diagnoses: [
      { code: "Z01.7", name: "Laborchemische Ausschlussdiagnostik ohne Befund", status: "resolved" },
    ],
    progression: "Unauffällig.",
    treatmentResponse: "Magenschutz mit Pantoprazol 20mg bei Einnahme von Ibuprofen zeitweise verordnet.",
    unresolvedIssues: ["Keine internistischen Bedenken"],
    evidenceReferences: [
      { docId: "doc-7", docName: "Labor_Analysen_Entzuendungsmarker_Blutbild.pdf", page: 4, excerpt: "Sämtliche Entzündungs- und Organmarker im Referenzbereich." },
    ],
  },
];

export const initialFunctionalCapacity: FunctionalCapacityItem[] = [
  {
    id: "fc-1",
    dimension: "Heben & Tragen von Lasten",
    category: "physical",
    status: "Schwer eingeschränkt",
    description: "Heben von Lasten über 10 kg ist aufgrund des operierten Segmentes L4/L5 dauerhaft kontraindiziert.",
    factualEvidence: "Reha-Abschlussbericht S. 19; Neurochirurgischer OP-Bericht S. 2.",
    aiInference: "Verbleibende Belastbarkeit bis 10kg gelegentlich, bis 5kg regelmäßig zumutbar.",
    confidenceLevel: 98,
    citedRecords: [
      { docName: "Reha_Abschlussbericht_Bad_Sassendorf.pdf", page: 19 },
      { docName: "OP_Bericht_Mikrochirurgische_Sequestrektomie.pdf", page: 2 },
    ],
  },
  {
    id: "fc-2",
    dimension: "Geh- & Stehfähigkeit",
    category: "physical",
    status: "Mäßig eingeschränkt",
    description: "Gehstrecke ohne Pause auf ca. 1.000 Meter limitiert. Anhaltendes Stehen auf 20-30 Minuten begrenzt.",
    factualEvidence: "Sozialmedizinische Leistungsbeurteilung Reha Bad Sassendorf S. 21.",
    aiInference: "Stehende Tätigkeiten erfordern regelmäßige Haltungswechsel und Entlastungsmöglichkeiten.",
    confidenceLevel: 95,
    citedRecords: [
      { docName: "Reha_Abschlussbericht_Bad_Sassendorf.pdf", page: 21 },
    ],
  },
  {
    id: "fc-3",
    dimension: "Sitzen & Zwangshaltungen",
    category: "physical",
    status: "Mäßig eingeschränkt",
    description: "Dauerhaftes ruhiges Sitzen führt nach 45 Minuten zu Zunahme der Lumbalien. Rumpfbeuge- und Verdrehhaltungen unzumutbar.",
    factualEvidence: "Hausärztliche Verlaufsdokumentation Dr. Krüger S. 12.",
    aiInference: "Arbeitsplatz muss ergonomisch mit dynamischem Sitz-Steh-Tisch ausgestattet sein.",
    confidenceLevel: 94,
    citedRecords: [
      { docName: "Hausarzt_Praxis_Dr_Krueger_Chronik.pdf", page: 12 },
    ],
  },
  {
    id: "fc-4",
    dimension: "Konzentration & Geistige Belastbarkeit",
    category: "cognitive",
    status: "Gering eingeschränkt",
    description: "Keine hirnorganischen Defizite. Leichte Ablenkbarkeit bei Schmerzspitzen unter Medikation (Pregabalin).",
    factualEvidence: "Psychiatrisches Gutachten Dr. Franke S. 8.",
    aiInference: "Vollschichtiges geistiges Leistungsvermögen für administrative/kaufmännische Tätigkeiten gegeben.",
    confidenceLevel: 96,
    citedRecords: [
      { docName: "Psychiatrisches_Zusatzgutachten_Schmerz.pdf", page: 8 },
    ],
  },
  {
    id: "fc-5",
    dimension: "Stresstoleranz & Psychische Resilienz",
    category: "psychological",
    status: "Gering eingeschränkt",
    description: "Adäquate Anpassung an die Situation. Vorübergehende Belastungseinschränkung unter hoher Zeitdruck-Exposition.",
    factualEvidence: "Psychiatrisches Zusatzgutachten S. 15.",
    aiInference: "Vermeidung von extremer Akkord- und Fließbandarbeit empfohlen.",
    confidenceLevel: 92,
    citedRecords: [
      { docName: "Psychiatrisches_Zusatzgutachten_Schmerz.pdf", page: 15 },
    ],
  },
  {
    id: "fc-6",
    dimension: "Soziale Interaktion & Teamfähigkeit",
    category: "social",
    status: "Normal",
    description: "Vollkommen intakte soziale Kompetenz, kooperativ im Behandlungsteam und am Arbeitsplatz.",
    factualEvidence: "Reha-Abschlussbericht Bad Sassendorf S. 14.",
    aiInference: "Keinerlei Einschränkungen im Umgang mit Kunden, Kollegen oder Vorgesetzten.",
    confidenceLevel: 99,
    citedRecords: [
      { docName: "Reha_Abschlussbericht_Bad_Sassendorf.pdf", page: 14 },
    ],
  },
];

export const initialDraftVariants: GutachtenDraftVariant[] = [
  {
    id: "detailed_expert",
    title: "1. Ausführliches Klinisch-Sozialmedizinisches Obergutachten",
    subtitle: "Empfohlene Fassung mit maximaler Evidenzabdeckung (S2k & AWMF-konform)",
    pageEstimate: "7 Seiten (Ausführlich)",
    isRecommended: true,
    completenessScore: 98,
    evidenceCoverageScore: 97,
    sections: [
      {
        id: "sec-1",
        title: "I. Gutachtlicher Auftrag & Patientendaten",
        content: `Im Auftrag der Berufsgenossenschaft Holz und Metall (BGHM, Az. BG-2026-9901-A) wird das vorliegende medizinische Obergutachten für Herrn Thomas Müller, geb. am 14.11.1982, erstellt.

Ziel der Begutachtung ist die verbindliche Feststellung des Ursachenzusammenhangs zwischen dem anerkannten Arbeitsunfall vom 12.03.2025 (Hebstrauma beim Heben einer 45 kg schweren Metallkiste) und dem nachgewiesenen L4/L5-Bandscheibenvorfall links mit konsekutiver L5-Radikulopathie sowie die Bewertung der verbleibenden Minderung der Erwerbsfähigkeit (MdE).`,
      },
      {
        id: "sec-2",
        title: "II. Vorerkrankungen & Akteneinsicht (Anamnese)",
        content: `Aus den übergebenen Behandlungsakten (Gesamtumfang 248 Seiten) geht hervor, dass beim Versicherten bis zum 12.03.2025 keine behandlungsbedürftigen lumbalen Vorschäden oder vorangegangenen Arbeitsunfähigkeitszeiten wegen Bandscheibenerkrankungen dokumentiert sind.

Am 12.03.2025 kam es beim Anheben einer Kiste (Gewicht 45 kg) unter gleichzeitiger Rumpfdrehung zu einem plötzlichen, einschneidenden Schmerzereignis im Lendenwirbelbereich mit unmittelbarer Ausstrahlung in die Außenseite des linken Oberschenkels und den Fußrücken (Dermatome L5).`,
      },
      {
        id: "sec-3",
        title: "III. Chronologischer Behandlungs- & Diagnostikverlauf",
        content: `- 12.03.2025: Erstversorgung Hausarzt Dr. Krüger, Verordnung von Analgetika.
- 20.03.2025: Stationäre Aufnahme Klinikum Köln Merheim bei Fußheberparese Grad 3-4/5.
- 28.03.2025: MRT LWS (Radiologie Köln-Süd): Frischer mediolateraler Disc-Herniationsbefund L4/L5 links.
- 04.04.2025: Mikrochirurgische Sequestrektomie L4/L5 links im St. Vinzenz Hospital.
- 14.05.2025: Neurologisches Konsil Dr. Braun mit EMG-Nachweis neurogener Denervierungsmuster L5.
- 22.06.2025: Abschluss Reha Bad Sassendorf mit sozialmedizinischer MdE-Empfehlung von 20%.`,
      },
      {
        id: "sec-4",
        title: "IV. Fachärztliche Befundsynthese & Kausalitätsbeurteilung",
        content: `Die S2k-Leitlinie der AWMF 'Lumbale Radikulopathie' sowie die biomechanischen Kriterien zur Begutachtung von Hebstraumen fordern für den Nachweis der Unfallkausalität:
1. Ein adäquates Unfallereignis mit plötzlicher Spitzenbelastung (Heben >40 kg in Beugung gesichert).
2. Den zeitnahen Nachweis einer akuten Radikularsymptomatik im passenden Segment (L5-Dermatom).
3. Den radiologischen Nachweis einer passenden Herniation ohne überwiegende altersunübliche Degeneration.

Sämtliche Kriterien sind im Falle von Herrn Thomas Müller lückenlos erfüllt. Es liegt somit eine rechtlich wesentliche Unfallkausalität im Sinne der gesetzlichen Unfallversicherung vor.`,
      },
      {
        id: "sec-5",
        title: "V. Sozialmedizinische Leistungsbeurteilung & MdE-Einschätzung",
        content: `Aufgrund der verbliebenen Restsymptomatik (Sensibilitätsstörung L5 links, Schmerzzunahme bei Belastung, Einschränkung der Hebe- und Tragefähigkeit auf max. 10 kg) beträgt die Minderung der Erwerbsfähigkeit (MdE) auf dem allgemeinen Arbeitsmarkt dauerhaft 20 v.H. (zwanzig vom Hundert).

Das Leistungsvermögen für die bisherige Tätigkeit als Schlosser/Metallbauer ist aufgehoben. Für leichte bis mittelschwere Tätigkeiten in wechselnder Körperhaltung besteht ein vollschichtiges Leistungsvermögen (6 Stunden und mehr).`,
      },
      {
        id: "sec-6",
        title: "VI. Zusammenfassung, Prognose & Offene Fragen",
        content: `Prognose: Bei konsequenter physiotherapeutischer Eigenübung und schmerztherapeutischer Einstellung ist von einem stabilen Zustand auszugehen. Ein erneuter operativer Eingriff ist derzeit nicht indiziert.

Empfehlung: Gewährung von Leistungen zur Teilhabe am Arbeitsleben (LTA) zwecks Umschulung in ein körperlich leichtes Berufsfeld.`,
      },
    ],
  },
  {
    id: "insurance_oriented",
    title: "2. Krankenkassen- & Berufsgenossenschafts-Gutachten",
    subtitle: "Fokussiert auf BGHM-Leistungsansprüche, Verletztengeld und Rehabilitationsbedarf",
    pageEstimate: "5 Seiten (Kompakt)",
    isRecommended: false,
    completenessScore: 92,
    evidenceCoverageScore: 91,
    sections: [
      {
        id: "sec-1",
        title: "I. Versicherungsrechtliche Grundlagen & Leistungsanspruch",
        content: `Kurzgutachten zur Prüfung des Verletztengeldanspruchs und der Gewährung einer Verletztenrente gemäß § 56 SGB VII für Thomas Müller (BG-Az. BG-2026-9901-A).`,
      },
      {
        id: "sec-2",
        title: "II. Unfallhergang & Kausalitätsprüfung",
        content: `Der Vorfall vom 12.03.2025 erfüllt den Tatbestand des Arbeitsunfalls. Die biomechanische Belastungsgrenze wurde durch das Heben von 45kg überschritten. Vorerkrankungen im Sinne der BG-Leistungsordnung liegen nicht vor.`,
      },
      {
        id: "sec-3",
        title: "III. Einschätzung der Minderung der Erwerbsfähigkeit (MdE)",
        content: `Es wird eine Rentenleistung nach einer MdE von 20% ab Ablauf des Verletztengeldbezugs vorgeschlagen.`,
      },
    ],
  },
  {
    id: "court_friendly",
    title: "3. Gerichtsnahes Strukturgutachten (§ 109 SGG)",
    subtitle: "Strikte Gliederung gemäß sozialgerichtlichen Beweisbeschlüssen mit Urteilsrelevanz",
    pageEstimate: "8 Seiten (Gerichtsformal)",
    isRecommended: false,
    completenessScore: 95,
    evidenceCoverageScore: 94,
    sections: [
      {
        id: "sec-1",
        title: "I. Beantwortung der Beweisfragen des Sozialgerichts",
        content: `Frage 1: Liegt beim Kläger ein Körperschaden vor?
Antwort: Ja, Zustand nach operativem Eingriff bei L4/L5 Bandscheibenvorfall mit persistierender L5-Radikulopathie links.

Frage 2: Ist dieser Schaden mit Wahrscheinlichkeit auf den Unfall vom 12.03.2025 zurückzuführen?
Antwort: Ja, die medizinische und rechtliche Kausalität ist uneingeschränkt zu bejahen.`,
      },
    ],
  },
  {
    id: "concise_executive",
    title: "4. Kompaktgutachten für Eilentscheidungen",
    subtitle: "Prägnante 2-Seiten Übersicht für Schnellprüfungen und Voreinschätzungen",
    pageEstimate: "2 Seiten (Kompakt)",
    isRecommended: false,
    completenessScore: 84,
    evidenceCoverageScore: 82,
    sections: [
      {
        id: "sec-1",
        title: "Executive Summary & Kernfeststellungen",
        content: `Kausalität: Bejaht. Diagnosen: L4/L5 Bandscheibenvorfall links mit L5-Syndrom. MdE: 20%. Empfehlung: Umschulung via LTA.`,
      },
    ],
  },
];

export const initialQualityControlItems: QualityControlItem[] = [
  {
    id: "qc-1",
    severity: "high",
    type: "conflicting_diagnoses",
    title: "Mögliche ICD-10 Überschneidung: M51.1 vs M54.16",
    description: "Der Hausarzt verwendet M54.16 (Radikulopathie LWS allgemein), während die Neurochirurgie M51.1 (Bandscheibenschaden mit Radikulopathie) codiert.",
    affectedDocs: ["Klinikum_Koeln_Entlassungsbericht_2025-03-20.pdf", "Hausarzt_Praxis_Dr_Krueger_Chronik.pdf"],
    suggestedResolution: "Verwenden Sie primär M51.1 im Hauptgutachten, da der Bandscheibenvorfall MRT-diagnostisch gesichert wurde.",
    isResolved: false,
  },
  {
    id: "qc-2",
    severity: "medium",
    type: "inconsistent_date",
    title: "Datumsabweichung beim Erstversorgungsbericht",
    description: "Die BG-Unfallanzeige gibt als Unfallzeitpunkt 12.03.2025 10:15 Uhr an, die Notfallaufnahme verzeichnete die Ersterfassung am 12.03.2025 14:30 Uhr.",
    affectedDocs: ["BG_Schriftverkehr_Unfallanzeige.pdf", "Hausarzt_Praxis_Dr_Krueger_Chronik.pdf"],
    suggestedResolution: "Lückenlose zeitliche Korrelation liegt vor; die 4-stündige Differenz erklärt sich durch den Transport und ist unschädlich.",
    isResolved: true,
  },
  {
    id: "qc-3",
    severity: "low",
    type: "duplicate_report",
    title: "Doppeltes Dokument erkannt (Laborwerte)",
    description: "Seite 1-4 von Labor_Analysen_Entzuendungsmarker_Blutbild.pdf sind identisch mit Ueberweisungen_und_Konsilberichte.pdf (Anhang).",
    affectedDocs: ["Labor_Analysen_Entzuendungsmarker_Blutbild.pdf", "Ueberweisungen_und_Konsilberichte.pdf"],
    suggestedResolution: "Automatische Bereinigung durchgeführt. Daten wurden nicht doppelt gezählt.",
    isResolved: true,
  },
];

export const initialConsensusOutputs: ConsensusModelOutput[] = [
  {
    modelId: "clara_gemini",
    modelName: "Dr. Clara (Med-Gemini)",
    avatarColor: "from-cyan-500 to-teal-500",
    findingTitle: "Klinisch-Radiologische Korrelation",
    assessmentText: "Die MRT-Befunde vom 28.03.2025 belegen eindeutig einen frischen mediolateralen Sequestrationsvorfall L4/L5 links. Dieser korreliert exakt mit der klinisch nachgewiesenen L5-Fußheberparese. Ein altersbedingter Verschleiß als Hauptursache ist radiologisch ausgeschlossen.",
    confidenceScore: 98,
    agreesWithConsensus: true,
  },
  {
    modelId: "eric_claude",
    modelName: "Dr. Eric (Claude 3.5 Sonnet)",
    avatarColor: "from-amber-500 to-orange-500",
    findingTitle: "S2k-Leitlinien & BG-Rechtsprechung",
    assessmentText: "Das Hebeereignis (45 kg Last unter Torsion) stellt ein anerkanntes kinetisches Trauma im Sinne der AWMF-S2k-Richtlinie dar. Der zeitliche Zusammenhang innerhalb weniger Stunden ist lückenlos nachgewiesen. Die vorgeschlagene MdE von 20% entspricht der ständigen BG-Praxis.",
    confidenceScore: 96,
    agreesWithConsensus: true,
  },
  {
    modelId: "marcus_gpt4",
    modelName: "Dr. Marcus (GPT-4o)",
    avatarColor: "from-purple-500 to-indigo-500",
    findingTitle: "Biomechanische Vektoranalyse",
    assessmentText: "Die biomechanische Kraftberechnung ergibt beim Anheben einer 45 kg Kiste aus gebückter Haltung eine lumbale Scherbelastung von >4.800 Newton im Segment L4/L5. Diese Belastung überschreitet die physiologische Belastungsgrenze der Anulus-fibrosus-Fasern deutlich.",
    confidenceScore: 95,
    agreesWithConsensus: true,
  },
  {
    modelId: "gratsiano_deepseek",
    modelName: "Dr. Gratsiano (UDO-R1 (Dr. Gratsiano))",
    avatarColor: "from-rose-500 to-pink-500",
    findingTitle: "Kognitive Evidenzsynthese & CoT",
    assessmentText: "Cross-Evaluierung von EMG-Leitgeschwindigkeiten des M. tibialis anterior (Abfall auf 42 m/s) mit der L4/L5 MRT-Schnittführung. Der seitliche Kompressionsvektor der L5-Wurzel ist konsolidiert. Chronifizierungsrisiko ist mäßig; konservative Optionen sind ausgereizt. MdE 20% rechtlich und medizinisch unstrittig.",
    confidenceScore: 97,
    agreesWithConsensus: true,
  },
];
